# Generated by Django 4.2.29 on 2026-04-03 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('prefer_not', 'Prefer Not to Say')], default='prefer_not', max_length=20)),
                ('service', models.CharField(choices=[('swedish_massage', 'Swedish Massage'), ('deep_tissue', 'Deep Tissue Massage'), ('hot_stone', 'Hot Stone Therapy'), ('aromatherapy', 'Aromatherapy Massage'), ('facial', 'Luxury Facial'), ('body_wrap', 'Body Wrap Treatment'), ('foot_reflexology', 'Foot Reflexology'), ('couples_massage', 'Couples Massage'), ('prenatal_massage', 'Prenatal Massage'), ('sports_massage', 'Sports Massage')], max_length=50)),
                ('duration', models.CharField(choices=[('30', '30 Minutes'), ('60', '60 Minutes'), ('90', '90 Minutes'), ('120', '120 Minutes')], max_length=10)),
                ('preferred_date', models.DateField()),
                ('preferred_time', models.TimeField()),
                ('therapist_preference', models.CharField(choices=[('any', 'No Preference'), ('female', 'Female Therapist'), ('male', 'Male Therapist')], default='any', max_length=20)),
                ('health_conditions', models.TextField(blank=True, null=True)),
                ('allergies', models.TextField(blank=True, null=True)),
                ('pressure_preference', models.CharField(choices=[('light', 'Light'), ('medium', 'Medium'), ('firm', 'Firm'), ('deep', 'Deep')], default='medium', max_length=20)),
                ('special_requests', models.TextField(blank=True, null=True)),
                ('consent_given', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exported', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
