# Generated by Django 4.2.29 on 2026-04-03 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('service', models.CharField(choices=[('foot_massage', 'Foot Massage'), ('head_massage', 'Head Massage'), ('thigh_massage', 'Thigh Massage'), ('shoulder_massage', 'Shoulder Massage'), ('back_massage', 'Back Massage')], max_length=50)),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=5)),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='booking',
            name='exported',
        ),
        migrations.AlterField(
            model_name='booking',
            name='duration',
            field=models.CharField(choices=[('30', '30 Minutes'), ('60', '60 Minutes'), ('90', '90 Minutes'), ('120', '120 Minutes')], default='60', max_length=10),
        ),
        migrations.AlterField(
            model_name='booking',
            name='service',
            field=models.CharField(choices=[('foot_massage', 'Foot Massage'), ('head_massage', 'Head Massage'), ('thigh_massage', 'Thigh Massage'), ('shoulder_massage', 'Shoulder Massage'), ('back_massage', 'Back Massage')], max_length=50),
        ),
    ]
