# Generated by Django 4.2.29 on 2026-04-03 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_sitevisit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='therapist_preference',
        ),
        migrations.AddField(
            model_name='booking',
            name='client_type',
            field=models.CharField(choices=[('female', 'Female'), ('couple', 'Couple')], default='female', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('postponed', 'Postponed')], default='confirmed', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(fields=('preferred_date', 'preferred_time'), name='unique_booking_slot'),
        ),
    ]
