# Generated by Django 4.2.29 on 2026-04-03 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_remove_booking_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='partner_age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='partner_gender',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='partner_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
